# Generated by Django 6.0.6 on 2026-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='membership_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('guest', 'Guest')], default='student', max_length=20),
        ),
    ]
