# Generated by Django 6.0.6 on 2026-07-03 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('returned', 'Returned'), ('renewal_approved', 'Renewal Approved'), ('renewal_rejected', 'Renewal Rejected'), ('fine_issued', 'Fine Issued'), ('general', 'General')], default='general', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
