# Generated by Django 6.0.6 on 2026-08-11 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook_file',
            field=models.FileField(blank=True, help_text='Optional PDF - lets patrons read the book online from its detail page.', null=True, upload_to='book_ebooks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
