# Generated by Django 6.0.6 on 2026-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_period_days', models.PositiveIntegerField(default=14, help_text='Default loan period for student members.')),
                ('faculty_loan_period_days', models.PositiveIntegerField(default=30, help_text='Loan period for faculty members.')),
                ('guest_loan_period_days', models.PositiveIntegerField(default=7, help_text='Loan period for guest members.')),
                ('max_active_loans_student', models.PositiveIntegerField(default=5)),
                ('max_active_loans_faculty', models.PositiveIntegerField(default=10)),
                ('max_active_loans_guest', models.PositiveIntegerField(default=3)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('max_renewals', models.PositiveIntegerField(default=1)),
                ('renewal_period_days', models.PositiveIntegerField(default=7)),
                ('due_soon_reminder_days', models.PositiveIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Library policy',
                'verbose_name_plural': 'Library policy',
            },
        ),
    ]
